### PR TITLE
Note collection index struct

### PR DESCRIPTION
**Pull request by massimobio**
As per #121 I converted NoteCollectionIndex from a tuple to a struct. (I misspelled tuple as tuplet in the commit message 🤦🏼‍♂️)
I noticed that the ```noteFromMeasure``` method in MeasureTests could be simplified if we passed a NoteCollectionIndex parameter instead each value separately but the visibility is internal.
What would we be the best thing to do?

### CODE REVIEW

**Comment by drumnkyle** [comment]
Good thinking that NoteCollectionIndex can be used in the test method as well. Let's make that change here. In Swift, if something is marked `internal`, you can access it from a test if you use `@testable import FrameworkName`, which is already being done. Therefore, you should be able to access it. Since it is a struct within a class, you will need to access it by doing `Measure.NoteCollectionIndex`.

**Comment by drumnkyle** [comment]
The other places to do this are listed in [this doc](https://github.com/drumnkyle/music-notation-core/blob/master/docs/indexing-methodology.md). I would recommend reading the doc as it will explain more about what this is and why we created it. The bottom of the doc lists the usages. Also, if you have a different or better idea, let us know. This is the pattern we came up.

It'll probably make sense to have separate commits to this PR for each one (you can use the label "WIP" to indicate it's not done yet). Then, we can merge it all at once and close the issue.

**Comment by massimobio** [comment]
Looks like it's not worth changing that private method in the MeasureTests as it's in use in a lot of places where the syntax would become more verbose.

This latest commit replaces the tuple with struct Staff.MeasureIndex. There are a couple of places where you had used measureIndex for local parameter names so I changed those to be simply index. The keyword index is getting a bit overloaded with different meanings...

**Comment by drumnkyle** [comment]
Once you resolve the conflicts and feel this is ready, you can remove the WIP tag and let me know and I'll review.

**Comment by massimobio** [comment]
Fixed this. Piece of cake in comparison to the clef stuff...

**Pull request merged**
